// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneymanager.Services.NetworthAPI.Data;

#nullable disable

namespace Moneymanager.Services.NetworthAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moneymanager.Services.NetworthAPI.Models.FinancialAsset", b =>
                {
                    b.Property<int>("FinancialAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialAssetId"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<double>("AssetValue")
                        .HasColumnType("float");

                    b.Property<double?>("GrowthRate")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FinancialAssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Moneymanager.Services.NetworthAPI.Models.FinancialLiability", b =>
                {
                    b.Property<int>("FinancialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialId"));

                    b.Property<double>("AmountOwed")
                        .HasColumnType("float");

                    b.Property<double?>("InterestRate")
                        .HasColumnType("float");

                    b.Property<string>("LiabilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiabilityType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FinancialId");

                    b.ToTable("Liabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
