// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneymanager.Services.TransactionAPI.Data;

#nullable disable

namespace Moneymanager.Services.TransactionAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251217010038_addBalanceUpdateFlag")]
    partial class addBalanceUpdateFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.AccountTransactions", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<bool>("BalanceUpdated")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("SubcategoryID");

                    b.HasIndex("TransactionTypeID");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Income",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Auto & Transport",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Housing",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Bills & Utilities",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Food & Dining",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Shopping",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Gifts & Donations",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Financial",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Children",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Health & Fitness",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Travel & Fun",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Business Expenses",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Other",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryTypeID"));

                    b.Property<string>("CategoryTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryTypeID");

                    b.ToTable("CategoryTypes");

                    b.HasData(
                        new
                        {
                            CategoryTypeID = 1,
                            CategoryTypeName = "Income",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryTypeID = 2,
                            CategoryTypeName = "Variable",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryTypeID = 3,
                            CategoryTypeName = "Fixed",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CategoryTypeID = 4,
                            CategoryTypeName = "Other",
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Freelance"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Rental Income"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Investment Income"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Bonus"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Interest"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Other Income"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            CategoryId = 2,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Auto Payment"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Public Transportation"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Fuel & Gasoline"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Ridesharing & Taxis"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Vehicle Maintenance & Repairs"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Parking & Tolls"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Mortgage"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Rent"
                        },
                        new
                        {
                            SubcategoryID = 15,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Property Tax"
                        },
                        new
                        {
                            SubcategoryID = 16,
                            CategoryId = 3,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Improvements"
                        },
                        new
                        {
                            SubcategoryID = 17,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Security"
                        },
                        new
                        {
                            SubcategoryID = 18,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Gas"
                        },
                        new
                        {
                            SubcategoryID = 19,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Electricity"
                        },
                        new
                        {
                            SubcategoryID = 20,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Internet & Streaming"
                        },
                        new
                        {
                            SubcategoryID = 21,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Water"
                        },
                        new
                        {
                            SubcategoryID = 22,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Rental Equipment"
                        },
                        new
                        {
                            SubcategoryID = 23,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Phone"
                        },
                        new
                        {
                            SubcategoryID = 24,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Groceries"
                        },
                        new
                        {
                            SubcategoryID = 25,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Coffee Shops"
                        },
                        new
                        {
                            SubcategoryID = 26,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Fast Food"
                        },
                        new
                        {
                            SubcategoryID = 27,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Restaurants"
                        },
                        new
                        {
                            SubcategoryID = 28,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Shopping"
                        },
                        new
                        {
                            SubcategoryID = 29,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Clothing & Accessories"
                        },
                        new
                        {
                            SubcategoryID = 30,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Furniture & Home Decor"
                        },
                        new
                        {
                            SubcategoryID = 31,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Appliances & Electronics"
                        },
                        new
                        {
                            SubcategoryID = 32,
                            CategoryId = 7,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Gifts"
                        },
                        new
                        {
                            SubcategoryID = 33,
                            CategoryId = 7,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Charity"
                        },
                        new
                        {
                            SubcategoryID = 34,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Student Loans & Repayments"
                        },
                        new
                        {
                            SubcategoryID = 35,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Financial Fees"
                        },
                        new
                        {
                            SubcategoryID = 36,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Taxes"
                        },
                        new
                        {
                            SubcategoryID = 37,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Cash & Withdrawals"
                        },
                        new
                        {
                            SubcategoryID = 38,
                            CategoryId = 8,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Car Insurance"
                        },
                        new
                        {
                            SubcategoryID = 39,
                            CategoryId = 8,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Home Insurance"
                        },
                        new
                        {
                            SubcategoryID = 40,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Other Insurance"
                        },
                        new
                        {
                            SubcategoryID = 41,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Savings"
                        },
                        new
                        {
                            SubcategoryID = 42,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Investments"
                        },
                        new
                        {
                            SubcategoryID = 43,
                            CategoryId = 9,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Childcare Expenses"
                        },
                        new
                        {
                            SubcategoryID = 44,
                            CategoryId = 9,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Child Activities"
                        },
                        new
                        {
                            SubcategoryID = 45,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Medical"
                        },
                        new
                        {
                            SubcategoryID = 46,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Dentist"
                        },
                        new
                        {
                            SubcategoryID = 47,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Fitness"
                        },
                        new
                        {
                            SubcategoryID = 48,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Travel & Vacations"
                        },
                        new
                        {
                            SubcategoryID = 49,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Entertainment & Leisure"
                        },
                        new
                        {
                            SubcategoryID = 50,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Hobbies & Crafts"
                        },
                        new
                        {
                            SubcategoryID = 51,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Pets"
                        },
                        new
                        {
                            SubcategoryID = 52,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Fun Money"
                        },
                        new
                        {
                            SubcategoryID = 53,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Personal Care"
                        },
                        new
                        {
                            SubcategoryID = 54,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Subscriptions & Memberships"
                        },
                        new
                        {
                            SubcategoryID = 55,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Advertising & Marketing"
                        },
                        new
                        {
                            SubcategoryID = 56,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Office Supplies"
                        },
                        new
                        {
                            SubcategoryID = 57,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Software & Tools"
                        },
                        new
                        {
                            SubcategoryID = 58,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Business Utilities"
                        },
                        new
                        {
                            SubcategoryID = 59,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Employee Salaries"
                        },
                        new
                        {
                            SubcategoryID = 60,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Business Travel"
                        },
                        new
                        {
                            SubcategoryID = 61,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Business Insurance"
                        },
                        new
                        {
                            SubcategoryID = 62,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Business Rent"
                        },
                        new
                        {
                            SubcategoryID = 63,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Other Business Expenses"
                        },
                        new
                        {
                            SubcategoryID = 64,
                            CategoryId = 13,
                            CategoryTypeId = 4,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Uncategorized"
                        },
                        new
                        {
                            SubcategoryID = 65,
                            CategoryId = 13,
                            CategoryTypeId = 4,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SubcategoryName = "Miscellaneous Expenses"
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.TransaationType", b =>
                {
                    b.Property<int>("TransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionTypeID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionTypeID");

                    b.ToTable("TransacationTypes");

                    b.HasData(
                        new
                        {
                            TransactionTypeID = 1,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionTypeName = "Credit"
                        },
                        new
                        {
                            TransactionTypeID = 2,
                            CreatedDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TransactionTypeName = "Debit"
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.AccountTransactions", b =>
                {
                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.TransaationType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Subcategory", b =>
                {
                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CategoryType");
                });
#pragma warning restore 612, 618
        }
    }
}
