// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneymanager.Services.TransactionAPI.Data;

#nullable disable

namespace Moneymanager.Services.TransactionAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251206005149_seedAccounTransactions")]
    partial class seedAccounTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.AccountTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BankAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.ToTable("AccountTransactions");

                    b.HasData(
                        new
                        {
                            TransactionID = 1,
                            Amount = 1000.0,
                            BankAccountID = 1,
                            Category = "Income",
                            CategoryType = "Income",
                            Description = "Salary Deposit",
                            TransactionDate = new DateTime(2025, 12, 5, 19, 51, 48, 877, DateTimeKind.Local).AddTicks(7496),
                            Type = "Credit"
                        },
                        new
                        {
                            TransactionID = 2,
                            Amount = 100.0,
                            BankAccountID = 1,
                            Category = "Groceries",
                            CategoryType = "Variable",
                            Description = "No Frills",
                            TransactionDate = new DateTime(2025, 12, 4, 19, 51, 48, 877, DateTimeKind.Local).AddTicks(7574),
                            Type = "Debit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
