// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneymanager.Services.TransactionAPI.Data;

#nullable disable

namespace Moneymanager.Services.TransactionAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.AccountTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BankAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("SubcategoryID");

                    b.HasIndex("TransactionTypeID");

                    b.ToTable("AccountTransactions", (string)null);
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Income",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7370)
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Auto & Transport",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7373)
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Housing",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7375)
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Bills & Utilities",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7378)
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Food & Dining",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7380)
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Shopping",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7383)
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Gifts & Donations",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7386)
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Financial",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7388)
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Children",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7391)
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Health & Fitness",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7393)
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Travel & Fun",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7395)
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Business Expenses",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7398)
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Other",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7400)
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryTypeID"));

                    b.Property<string>("CategoryTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryTypeID");

                    b.ToTable("CategoryTypes", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryTypeID = 1,
                            CategoryTypeName = "Income",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7153)
                        },
                        new
                        {
                            CategoryTypeID = 2,
                            CategoryTypeName = "Variable",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7212)
                        },
                        new
                        {
                            CategoryTypeID = 3,
                            CategoryTypeName = "Fixed",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7216)
                        },
                        new
                        {
                            CategoryTypeID = 4,
                            CategoryTypeName = "Other",
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7218)
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("Subcategories", (string)null);

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7442),
                            SubcategoryName = "Freelance"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7446),
                            SubcategoryName = "Rental Income"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7449),
                            SubcategoryName = "Investment Income"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7452),
                            SubcategoryName = "Bonus"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7455),
                            SubcategoryName = "Interest"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            CategoryId = 1,
                            CategoryTypeId = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7457),
                            SubcategoryName = "Other Income"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            CategoryId = 2,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7460),
                            SubcategoryName = "Auto Payment"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7463),
                            SubcategoryName = "Public Transportation"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7466),
                            SubcategoryName = "Fuel & Gasoline"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7469),
                            SubcategoryName = "Ridesharing & Taxis"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7471),
                            SubcategoryName = "Vehicle Maintenance & Repairs"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7474),
                            SubcategoryName = "Parking & Tolls"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7477),
                            SubcategoryName = "Mortgage"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7480),
                            SubcategoryName = "Rent"
                        },
                        new
                        {
                            SubcategoryID = 15,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7482),
                            SubcategoryName = "Property Tax"
                        },
                        new
                        {
                            SubcategoryID = 16,
                            CategoryId = 3,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7485),
                            SubcategoryName = "Home Improvements"
                        },
                        new
                        {
                            SubcategoryID = 17,
                            CategoryId = 3,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7488),
                            SubcategoryName = "Home Security"
                        },
                        new
                        {
                            SubcategoryID = 18,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7490),
                            SubcategoryName = "Home Gas"
                        },
                        new
                        {
                            SubcategoryID = 19,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7493),
                            SubcategoryName = "Home Electricity"
                        },
                        new
                        {
                            SubcategoryID = 20,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7496),
                            SubcategoryName = "Internet & Streaming"
                        },
                        new
                        {
                            SubcategoryID = 21,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7499),
                            SubcategoryName = "Water"
                        },
                        new
                        {
                            SubcategoryID = 22,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7502),
                            SubcategoryName = "Home Rental Equipment"
                        },
                        new
                        {
                            SubcategoryID = 23,
                            CategoryId = 4,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7505),
                            SubcategoryName = "Phone"
                        },
                        new
                        {
                            SubcategoryID = 24,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7508),
                            SubcategoryName = "Groceries"
                        },
                        new
                        {
                            SubcategoryID = 25,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7510),
                            SubcategoryName = "Coffee Shops"
                        },
                        new
                        {
                            SubcategoryID = 26,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7513),
                            SubcategoryName = "Fast Food"
                        },
                        new
                        {
                            SubcategoryID = 27,
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7516),
                            SubcategoryName = "Restaurants"
                        },
                        new
                        {
                            SubcategoryID = 28,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7519),
                            SubcategoryName = "Shopping"
                        },
                        new
                        {
                            SubcategoryID = 29,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7521),
                            SubcategoryName = "Clothing & Accessories"
                        },
                        new
                        {
                            SubcategoryID = 30,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7524),
                            SubcategoryName = "Furniture & Home Decor"
                        },
                        new
                        {
                            SubcategoryID = 31,
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7527),
                            SubcategoryName = "Appliances & Electronics"
                        },
                        new
                        {
                            SubcategoryID = 32,
                            CategoryId = 7,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7529),
                            SubcategoryName = "Gifts"
                        },
                        new
                        {
                            SubcategoryID = 33,
                            CategoryId = 7,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7532),
                            SubcategoryName = "Charity"
                        },
                        new
                        {
                            SubcategoryID = 34,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7535),
                            SubcategoryName = "Student Loans & Repayments"
                        },
                        new
                        {
                            SubcategoryID = 35,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7538),
                            SubcategoryName = "Financial Fees"
                        },
                        new
                        {
                            SubcategoryID = 36,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7540),
                            SubcategoryName = "Taxes"
                        },
                        new
                        {
                            SubcategoryID = 37,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7543),
                            SubcategoryName = "Cash & Withdrawals"
                        },
                        new
                        {
                            SubcategoryID = 38,
                            CategoryId = 8,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7545),
                            SubcategoryName = "Car Insurance"
                        },
                        new
                        {
                            SubcategoryID = 39,
                            CategoryId = 8,
                            CategoryTypeId = 3,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7548),
                            SubcategoryName = "Home Insurance"
                        },
                        new
                        {
                            SubcategoryID = 40,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7551),
                            SubcategoryName = "Other Insurance"
                        },
                        new
                        {
                            SubcategoryID = 41,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7555),
                            SubcategoryName = "Savings"
                        },
                        new
                        {
                            SubcategoryID = 42,
                            CategoryId = 8,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7557),
                            SubcategoryName = "Investments"
                        },
                        new
                        {
                            SubcategoryID = 43,
                            CategoryId = 9,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7561),
                            SubcategoryName = "Childcare Expenses"
                        },
                        new
                        {
                            SubcategoryID = 44,
                            CategoryId = 9,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7563),
                            SubcategoryName = "Child Activities"
                        },
                        new
                        {
                            SubcategoryID = 45,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7566),
                            SubcategoryName = "Medical"
                        },
                        new
                        {
                            SubcategoryID = 46,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7569),
                            SubcategoryName = "Dentist"
                        },
                        new
                        {
                            SubcategoryID = 47,
                            CategoryId = 10,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7572),
                            SubcategoryName = "Fitness"
                        },
                        new
                        {
                            SubcategoryID = 48,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7574),
                            SubcategoryName = "Travel & Vacations"
                        },
                        new
                        {
                            SubcategoryID = 49,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7577),
                            SubcategoryName = "Entertainment & Leisure"
                        },
                        new
                        {
                            SubcategoryID = 50,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7580),
                            SubcategoryName = "Hobbies & Crafts"
                        },
                        new
                        {
                            SubcategoryID = 51,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7636),
                            SubcategoryName = "Pets"
                        },
                        new
                        {
                            SubcategoryID = 52,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7639),
                            SubcategoryName = "Fun Money"
                        },
                        new
                        {
                            SubcategoryID = 53,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7641),
                            SubcategoryName = "Personal Care"
                        },
                        new
                        {
                            SubcategoryID = 54,
                            CategoryId = 11,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7644),
                            SubcategoryName = "Subscriptions & Memberships"
                        },
                        new
                        {
                            SubcategoryID = 55,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7647),
                            SubcategoryName = "Advertising & Marketing"
                        },
                        new
                        {
                            SubcategoryID = 56,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7649),
                            SubcategoryName = "Office Supplies"
                        },
                        new
                        {
                            SubcategoryID = 57,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7652),
                            SubcategoryName = "Software & Tools"
                        },
                        new
                        {
                            SubcategoryID = 58,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7655),
                            SubcategoryName = "Business Utilities"
                        },
                        new
                        {
                            SubcategoryID = 59,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7658),
                            SubcategoryName = "Employee Salaries"
                        },
                        new
                        {
                            SubcategoryID = 60,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7662),
                            SubcategoryName = "Business Travel"
                        },
                        new
                        {
                            SubcategoryID = 61,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7665),
                            SubcategoryName = "Business Insurance"
                        },
                        new
                        {
                            SubcategoryID = 62,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7669),
                            SubcategoryName = "Business Rent"
                        },
                        new
                        {
                            SubcategoryID = 63,
                            CategoryId = 12,
                            CategoryTypeId = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7671),
                            SubcategoryName = "Other Business Expenses"
                        },
                        new
                        {
                            SubcategoryID = 64,
                            CategoryId = 13,
                            CategoryTypeId = 4,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7674),
                            SubcategoryName = "Uncategorized"
                        },
                        new
                        {
                            SubcategoryID = 65,
                            CategoryId = 13,
                            CategoryTypeId = 4,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7678),
                            SubcategoryName = "Miscellaneous Expenses"
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.TransacationType", b =>
                {
                    b.Property<int>("TransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionTypeID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionTypeID");

                    b.ToTable("TransacationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionTypeID = 1,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7751),
                            TransactionTypeName = "Credit"
                        },
                        new
                        {
                            TransactionTypeID = 2,
                            CreatedDate = new DateTime(2025, 12, 14, 19, 9, 49, 605, DateTimeKind.Local).AddTicks(7755),
                            TransactionTypeName = "Debit"
                        });
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.AccountTransaction", b =>
                {
                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.TransacationType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Moneymanager.Services.TransactionAPI.Models.Subcategory", b =>
                {
                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneymanager.Services.TransactionAPI.Models.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CategoryType");
                });
#pragma warning restore 612, 618
        }
    }
}
